import { expect, test } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { openDemo, openTab } from './demo'

test('analysis filters, daily drilldown and grouped sessions are keyboard accessible', async ({ page }, testInfo) => {
  test.skip(!['chromium-dark-100', 'chromium-light-125'].includes(testInfo.project.name))
  await openDemo(page, testInfo)
  await openTab(page, 'usage')
  await page.getByRole('button', { name: '全部历史', exact: true }).click()
  await expect(page.locator('.analysis-summary')).toBeVisible()
  await expect(page.locator('.analysis-filters')).toContainText('最早留存日期')
  await page.getByRole('combobox', { name: '指标', exact: true }).selectOption('amount')
  await expect(page.locator('.analysis-summary')).toContainText('API 等效金额')
  await expect(page.locator('.analysis-view')).toContainText('不当作零')
  await page.getByRole('combobox', { name: '指标', exact: true }).selectOption('tokens')
  const models = page.getByRole('combobox', { name: '模型', exact: true })
  const model = await models.locator('option').evaluateAll(options => (options as HTMLOptionElement[])
    .find(option => option.value && option.value !== 'unknown')?.value)
  expect(model).toBeTruthy()
  await models.selectOption(model!)
  await expect(page.locator('.analysis-summary')).toBeVisible()
  await expect(page.locator('.unknown-history')).toHaveCount(0)
  const day = page.locator('.daily-bars button').last()
  const label = await day.getAttribute('aria-label')
  await day.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: '自定义', exact: true })).toHaveAttribute('aria-pressed', 'true')
  const selectedDate = label!.slice(0, 10)
  await expect(page.getByLabel('开始日期', { exact: true })).toHaveValue(selectedDate)
  await expect(page.getByLabel('结束日期', { exact: true })).toHaveValue(selectedDate)
  await expect(models).toHaveValue(model!)
  await page.locator('.session-group > summary').first().focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.session-member').first()).toBeVisible()
  await expect(page.locator('.session-member').first()).toContainText('ID：')
  const results = await new AxeBuilder({ page }).include('#panel-usage').analyze()
  expect(results.violations).toEqual([])
})

test('invalid custom ranges report an error and recover on correction', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'chromium-dark-100')
  await openDemo(page, testInfo)
  await openTab(page, 'usage')
  await page.getByRole('button', { name: '自定义', exact: true }).click()
  await page.getByLabel('开始日期', { exact: true }).fill('2026-07-15')
  await page.getByLabel('结束日期', { exact: true }).fill('2026-07-14')
  await expect(page.locator('#panel-usage [role="alert"]')).toContainText('开始日期不能晚于结束日期')
  await page.getByLabel('开始日期', { exact: true }).fill('2026-07-01')
  await expect(page.locator('.analysis-summary')).toBeVisible()
  await expect(page.locator('#panel-usage [role="alert"]')).toHaveCount(0)
})
